/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author HP
 */
public class frm_finca extends javax.swing.JFrame {

    /**
     * Creates new form frm_finca
     */
    public frm_finca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btn_limpiarcultivos = new javax.swing.JButton();
        fnt_agregarfinca5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_limpiartabajador = new javax.swing.JButton();
        fnt_agregarfinca7 = new javax.swing.JButton();
        fnt_agregarfinca8 = new javax.swing.JButton();
        fnt_agregarfinca9 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        fnt_agregarfinca = new javax.swing.JButton();
        fnt_agregarfinca1 = new javax.swing.JButton();
        btn_limpiarfinca = new javax.swing.JButton();
        fnt_agregarfinca6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(233, 214, 175));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel1.setText("Sistema de Gestión de Fincas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(233, 214, 175));

        jPanel4.setBackground(new java.awt.Color(255, 255, 221));

        btn_limpiarcultivos.setBackground(new java.awt.Color(255, 255, 221));
        btn_limpiarcultivos.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btn_limpiarcultivos.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiarcultivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        btn_limpiarcultivos.setBorder(null);
        btn_limpiarcultivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarcultivosActionPerformed(evt);
            }
        });

        fnt_agregarfinca5.setBackground(new java.awt.Color(255, 255, 221));
        fnt_agregarfinca5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        fnt_agregarfinca5.setForeground(new java.awt.Color(255, 255, 255));
        fnt_agregarfinca5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        fnt_agregarfinca5.setBorder(null);
        fnt_agregarfinca5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnt_agregarfinca5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btn_limpiarcultivos, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(fnt_agregarfinca5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fnt_agregarfinca5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limpiarcultivos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 221));

        btn_limpiartabajador.setBackground(new java.awt.Color(255, 255, 221));
        btn_limpiartabajador.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btn_limpiartabajador.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiartabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        btn_limpiartabajador.setBorder(null);
        btn_limpiartabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiartabajadorActionPerformed(evt);
            }
        });

        fnt_agregarfinca7.setBackground(new java.awt.Color(255, 255, 221));
        fnt_agregarfinca7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        fnt_agregarfinca7.setForeground(new java.awt.Color(255, 255, 255));
        fnt_agregarfinca7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        fnt_agregarfinca7.setBorder(null);
        fnt_agregarfinca7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnt_agregarfinca7ActionPerformed(evt);
            }
        });

        fnt_agregarfinca8.setBackground(new java.awt.Color(255, 255, 221));
        fnt_agregarfinca8.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        fnt_agregarfinca8.setForeground(new java.awt.Color(255, 255, 255));
        fnt_agregarfinca8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/consulta-de-datos.png"))); // NOI18N
        fnt_agregarfinca8.setBorder(null);
        fnt_agregarfinca8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnt_agregarfinca8ActionPerformed(evt);
            }
        });

        fnt_agregarfinca9.setBackground(new java.awt.Color(255, 255, 221));
        fnt_agregarfinca9.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        fnt_agregarfinca9.setForeground(new java.awt.Color(255, 255, 255));
        fnt_agregarfinca9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/granja.png"))); // NOI18N
        fnt_agregarfinca9.setBorder(null);
        fnt_agregarfinca9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnt_agregarfinca9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_limpiartabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(fnt_agregarfinca9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addComponent(fnt_agregarfinca8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38)
                        .addComponent(fnt_agregarfinca7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_limpiartabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fnt_agregarfinca8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnt_agregarfinca9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnt_agregarfinca7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 221));

        fnt_agregarfinca.setBackground(new java.awt.Color(255, 255, 221));
        fnt_agregarfinca.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        fnt_agregarfinca.setForeground(new java.awt.Color(255, 255, 255));
        fnt_agregarfinca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/granja.png"))); // NOI18N
        fnt_agregarfinca.setBorder(null);
        fnt_agregarfinca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnt_agregarfincaActionPerformed(evt);
            }
        });

        fnt_agregarfinca1.setBackground(new java.awt.Color(255, 255, 221));
        fnt_agregarfinca1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        fnt_agregarfinca1.setForeground(new java.awt.Color(255, 255, 255));
        fnt_agregarfinca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/consulta-de-datos.png"))); // NOI18N
        fnt_agregarfinca1.setBorder(null);
        fnt_agregarfinca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnt_agregarfinca1ActionPerformed(evt);
            }
        });

        btn_limpiarfinca.setBackground(new java.awt.Color(255, 255, 221));
        btn_limpiarfinca.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btn_limpiarfinca.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiarfinca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        btn_limpiarfinca.setBorder(null);
        btn_limpiarfinca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarfincaActionPerformed(evt);
            }
        });

        fnt_agregarfinca6.setBackground(new java.awt.Color(255, 255, 221));
        fnt_agregarfinca6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        fnt_agregarfinca6.setForeground(new java.awt.Color(255, 255, 255));
        fnt_agregarfinca6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        fnt_agregarfinca6.setBorder(null);
        fnt_agregarfinca6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnt_agregarfinca6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(fnt_agregarfinca, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(fnt_agregarfinca1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(fnt_agregarfinca6, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_limpiarfinca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_limpiarfinca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fnt_agregarfinca1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnt_agregarfinca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnt_agregarfinca6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnt_agregarfincaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnt_agregarfincaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnt_agregarfincaActionPerformed

    private void fnt_agregarfinca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnt_agregarfinca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnt_agregarfinca1ActionPerformed

    private void btn_limpiarfincaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarfincaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_limpiarfincaActionPerformed

    private void btn_limpiartabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiartabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_limpiartabajadorActionPerformed

    private void btn_limpiarcultivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarcultivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_limpiarcultivosActionPerformed

    private void fnt_agregarfinca5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnt_agregarfinca5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnt_agregarfinca5ActionPerformed

    private void fnt_agregarfinca6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnt_agregarfinca6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnt_agregarfinca6ActionPerformed

    private void fnt_agregarfinca7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnt_agregarfinca7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnt_agregarfinca7ActionPerformed

    private void fnt_agregarfinca8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnt_agregarfinca8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnt_agregarfinca8ActionPerformed

    private void fnt_agregarfinca9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnt_agregarfinca9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnt_agregarfinca9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_finca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_finca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_finca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_finca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_finca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_limpiarcultivos;
    private javax.swing.JButton btn_limpiarfinca;
    private javax.swing.JButton btn_limpiartabajador;
    private javax.swing.JButton fnt_agregarfinca;
    private javax.swing.JButton fnt_agregarfinca1;
    private javax.swing.JButton fnt_agregarfinca5;
    private javax.swing.JButton fnt_agregarfinca6;
    private javax.swing.JButton fnt_agregarfinca7;
    private javax.swing.JButton fnt_agregarfinca8;
    private javax.swing.JButton fnt_agregarfinca9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
